{
  "mesh": {
    "cores": [8, 8],
    "noc": {"topology": "mesh", "width_bits": 256, "link_latency_ns": 5}
  },
  "dram": {
    "banks": [32, 32, 8],
    "page_kb": 8
  },
  "geometry": {
    "macro_size_mm": [5.0, 2.0],
    "layers": {
      "logic": {"thickness_um": 50, "k_wmk": 120},
      "dram": {"thickness_um": 50, "k_wmk": 2},
      "tim": {"thickness_um": 20, "k_wmk": 5}
    },
    "cooling": {"type": "air", "h_wmk2k": 10000}
  },
  "dvfs": {
    "domains": [
      {"cores": "all", "steps_ghz": [2.0, 1.8, 1.6, 1.2], "trip_c": [80, 85, 90]}
    ]
  },
  "refresh": {
    "tref_base_us": 7.8,
    "tref_curve": [[40, 1.0], [55, 2.0], [70, 4.0], [85, 8.0]]
  }
}
